spring:
  profiles:
    active: dev,imagga

---

spring:
  profiles: dev
  datasource:
    url: jdbc:h2:file:./db/rdbms;AUTO_SERVER=TRUE
    driver: org.h2.Driver
    username: sa
    password:
    hikari:
      maximumPoolSize: 2
server:
  port: 9090
  error:
    include-message: always

flyway:
  url: jdbc:h2:file:./db/rdbms;AUTO_SERVER=TRUE
  schemas: PUBLIC
  user: sa
  password:
