CREATE TABLE IMAGES (
    IMAGES_PK BIGINT AUTO_INCREMENT PRIMARY KEY,
    IMAGE_ID CHAR(36) NOT NULL,
    IMAGE_LABEL VARCHAR(255)
);

CREATE UNIQUE INDEX IMAGE_ID_IDX ON IMAGES (IMAGE_ID);

CREATE TABLE OBJECTS (
    OBJECTS_PK BIGINT AUTO_INCREMENT PRIMARY KEY,
    OBJECT_NAME VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX OBJECTS_IDX ON OBJECTS (OBJECT_NAME);

CREATE TABLE IMAGE_OBJECT_MAP (
    IMAGES_PK BIGINT NOT NULL,
    OBJECTS_PK BIGINT NOT NULL,
    PRIMARY KEY (IMAGES_PK, OBJECTS_PK)
);

ALTER TABLE IMAGE_OBJECT_MAP ADD FOREIGN KEY (IMAGES_PK) REFERENCES IMAGES (IMAGES_PK);
ALTER TABLE IMAGE_OBJECT_MAP ADD FOREIGN KEY (OBJECTS_PK) REFERENCES OBJECTS (OBJECTS_PK);