INSERT INTO IMAGES (IMAGE_ID, IMAGE_LABEL) VALUES ('b0bff754-5181-417e-a85b-edd1f6d2da2c', 'TestImage');

INSERT INTO OBJECTS (OBJECT_NAME) VALUES ('Dog');
INSERT INTO OBJECTS (OBJECT_NAME) VALUES ('Cat');
INSERT INTO OBJECTS (OBJECT_NAME) VALUES ('Hamster');
INSERT INTO OBJECTS (OBJECT_NAME) VALUES ('Weasel');

INSERT INTO IMAGE_OBJECT_MAP (IMAGES_PK, OBJECTS_PK) VALUES (1, 1);
INSERT INTO IMAGE_OBJECT_MAP (IMAGES_PK, OBJECTS_PK) VALUES (1, 2);
INSERT INTO IMAGE_OBJECT_MAP (IMAGES_PK, OBJECTS_PK) VALUES (1, 3);
INSERT INTO IMAGE_OBJECT_MAP (IMAGES_PK, OBJECTS_PK) VALUES (1, 4);